### ISSUE TITLE
Django Search Function inside ForeignKey

### ISSUE THREAD

**Issue by khashashin** [datalets/blemmy#2]
I have a class with huge amount of data and another class which should take the title value from this class. How can I add a search function to _ForeignKey_ as you can see in following Image. Or does Django have a way to solve this problem?
![92y7g](https://user-images.githubusercontent.com/17837758/28748053-c4e44a74-74ad-11e7-917a-2924d3a61ccc.png)

```
class Menue(models.Model):
    title = models.CharField(max_length=255)
    panels = [
        FieldPanel('title', classname="col12"),
    ]
def __str__(self):
    return self.title

class Wochen(models.Model):
    menu_1 = models.ForeignKey(Menue,
    null=True, blank=True, on_delete=models.PROTECT, related_name="menu_1+")
    panels = [
        FieldPanel('menu_1', classname="col12"),
    ]
def __str__(self):
    return self.menu_1
````

**Comment by loleg** [comment]
There is a Wagtail extension that does the trick: https://github.com/takeflight/wagtailmodelchooser
